export
    const
    MESSAGE_SERVICE = "MESSAGE_SERVICE",
    UNIVERSITY_SERVICE = "UNIVERSITY_SERVICE",
    USER_SERVICE = "USER_SERVICE",
    MESSAGE_SERVICE_GQL = "MESSAGE_SERVICE_GQL",
    UNIVERSITY_SERVICE_GQL = "UNIVERSITY_SERVICE_GQL",
    USER_SERVICE_GQL = "USER_SERVICE_GQL"
