export const global = {
    subjects: [
        "Mathematics",
        "Philosophy",
        "Law",
        "Business",
        "Theology",
        "History",
        "Education",
        "English",
        "Biology",
        "Economics",
        "Writing",
        "Anthropology",
        "Political Science",
        "Humanities",
        "Chemistry",
        "Psychology",
        "Classics",
        "Medicine",
        "Languages",
        "Physics",
        "Literature",
        "Environmental Science",
        "Religion",
        "Art History",
        "Statistics",
        "Engineering",
        "Computer Science",
        "Environmental Studies",
        "Womens & Gender Studies",
        "Accounting",
        "Women's Studies",
        "Film",
        "Music",
        "Linguistics",
        "Journalism",
        "Foreign Languages & Literature",
        "Geology",
        "Theater",
        "Design",
        "Japanese",
        "International Studies",
        "Latin",
        "Government",
        "Hospitality",
        "Information Science",
        "Animation",
        "Arts & Sciences",
        "Physical Education",
        "Not Specified",
        "Social Science",
        "Sociology",
        "Marketing",
        "Arts  Sciences",
        "Social Work",
        "Academic Services",
        "South Asian Studies",
        "Science",
        "Biostatistics",
        "Criminal Justice",
        "Foreign Languages amp Literature",
        "Human & Evolutionary Biology",
        "Human amp Evolutionary Biology",
        "Management",
        "Womens amp Gender Studies",
        "African Studies",
        "Health Science",
        "Ethnic Studies",
        "Nursing",
        "Communication",
        "Fine Arts",
        "Education & Academic Advancement"
    ]
}
