export const majors = [
  "english",
  "mathematics",
  "psychology",
  "biology",
  "history",
  "business",
  "computer science",
  "chemistry",
  "education",
  "communication",
  "music",
  "science",
  "sociology",
  "economics",
  "philosophy",
  "accounting",
  "languages",
  "political science",
  "fine arts",
  "health science",
  "physics",
  "art history",
  "humanities",
  "nursing",
  "not specified",
  "theater",
  "criminal justice",
  "social science",
  "physical education",
  "religion",
  "management",
  "engineering",
  "anthropology",
  "marketing",
  "writing",
  "law",
  "social work",
  "graphic arts",
  "geography",
  "literature",
  "geology",
  "finance",
  "physical ed",
  "design",
  "information science",
  "medicine",
  "film",
  "art",
  "journalism",
  "women's studies",
  "theology",
  "ethnic studies",
  "international studies",
  "architecture",
  "agriculture",
  "classics",
  "spanish",
  "hospitality",
  "culinary arts",
  "french",
  "speech",
  "dance",
  "foreign languages",
  "counseling",
  "astronomy",
  "business administration",
  "german",
  "photography",
  "computer information systems",
  "environmental science",
  "reading",
  "english as a second language",
  "nutrition",
  "early childhood education",
  "japanese",
  "statistics",
  "religious studies",
  "child development",
  "automotive technology",
  "environmental studies",
  "electrical engineering",
  "library science",
  "technology",
  "anatomy",
  "information technology",
  "kinesiology",
  "biological sciences",
  "health",
  "mechanical engineering",
  "athletics",
  "speech communication",
  "chinese",
  "biochemistry",
  "african-american studies",
  "civil engineering",
  "earth science",
  "italian",
  "linguistics",
  "special education",
  "sign language",
  "academic services",
  "information systems",
  "interdisciplinary studies",
  "government",
  "administration",
  "human services",
  "family & consumer science",
  "honors",
  "interior design",
  "business law",
  "health & physical education",
  "select department",
  "welding",
  "behavioral sciences",
  "microbiology",
  "occupational therapy",
  "communication studies",
  "allied health",
  "american studies",
  "modern languages",
  "pharmacy",
  "leadership",
  "computer & informational tech.",
  "advisor",
  "russian",
  "physical therapy",
  "sports management",
  "fashion",
  "public administration",
  "graphic design",
  "art & design",
  "aviation",
  "asian studies",
  "emt & paramedic",
  "physical sciences",
  "freshman seminar",
  "chemical engineering",
  "human development",
  "general studies",
  "athletic training",
  "recreation",
  "communication disorders",
  "real estate",
  "military science",
  "biblical studies",
  "exercise & sport science",
  "student services",
  "cosmetology",
  "electronics",
  "administration of justice",
  "medical assisting",
  "computer applications",
  "arts & sciences",
  "physics & astronomy",
  "career development",
  "horticulture",
  "health  physical education",
  "paralegal",
  "speech & hearing sciences",
  "computer engineering",
  "art education",
  "natural sciences",
  "public health",
  "student development",
  "arabic",
  "army rotc",
  "academic skills development",
  "health education",
  "art  design",
  "fire technology",
  "university studies",
  "industrial technology",
  "theatre & dance",
  "communications",
  "elementary education",
  "dental hygiene",
  "exercise  sport science",
  "animal science",
  "fire science",
  "family  consumer science",
  "drafting",
  "computer  informational tech.",
  "construction",
  "entrepreneurship",
  "art amp design",
  "american sign language",
  "mass communications",
  "liberal arts & sciences",
  "dental assisting",
  "composition",
  "college success",
  "women",
  "engineering technology",
  "aerospace studies",
  "student success",
  "visual arts",
  "dramatic arts",
  "advertising",
  "respiratory therapy",
  "marine sciences",
  "foreign languages & literature",
  "electrical technology",
  "international business",
  "medical technology",
  "meteorology",
  "music education",
  "health information science",
  "latin american studies",
  "liberal studies",
  "library",
  "veterinary sciences",
  "freshman year experience",
  "criminology",
  "business technology",
  "business communications",
  "english language & literature",
  "exercise science",
  "african studies",
  "health amp physical education",
  "health care administration",
  "performing arts",
  "oceanography",
  "developmental studies",
  "biomedical",
  "emt  paramedic",
  "art studio",
  "history & political science",
  "latin",
  "child & family studies",
  "adult basic education",
  "arts  sciences",
  "industrial engineering",
  "legal studies",
  "gender studies",
  "foods & nutrition",
  "chicano studies",
  "human resources",
  "physiology",
  "psychology & sociology",
  "curriculum & instruction",
  "botany",
  "media arts",
  "media studies",
  "natural resources",
  "pharmacology",
  "liberal arts",
  "learning skills",
  "computer skills",
  "cultural studies",
  "electronics technology",
  "gerontology",
  "forestry",
  "theatre  dance",
  "dental",
  "cinema",
  "counseling & career planning",
  "ceramics",
  "exercise amp sport science",
  "radiological sciences",
  "music performance",
  "nutrition & foods",
  "physics  astronomy",
  "sports medicine",
  "graduate studies",
  "family amp consumer science",
  "ta",
  "judaic studies",
  "creative writing",
  "east asian studies",
  "educational leadership",
  "archaeology",
  "multimedia",
  "human resources management",
  "health administration",
  "neuroscience",
  "liberal arts  sciences",
  "sports",
  "speech  hearing sciences",
  "studio art",
  "global studies",
  "family studies",
  "office administration",
  "digital arts",
  "urban studies",
  "zoology",
  "construction management",
  "curriculum  instruction",
  "wellness",
  "electrical & comp. engineering",
  "ethics",
  "art & art history",
  "arts amp sciences",
  "film & television",
  "foreign languages  literature",
  "counselor education",
  "continuing education",
  "english language  literature",
  "educational psychology",
  "animation",
  "air conditioning & refrig.",
  "health & human performance",
  "health care studies",
  "health occupations",
  "life science",
  "social & behavioral sciences",
  "general education",
  "food science",
  "orientation",
  "justice studies",
  "computer amp informational tech.",
  "communication arts",
  "counseling & human services",
  "wildlife",
  "applied arts",
  "auto body",
  "american indian studies",
  "health & human services",
  "physics amp astronomy",
  "social sciences",
  "comparative literature",
  "broadcasting",
  "web design",
  "electrical  comp. engineering",
  "electronic engineering technol",
  "fitness",
  "foreign languages amp literature",
  "teaching & learning",
  "telecommunications",
  "drawing",
  "biomedical engineering",
  "business economics",
  "environment",
  "entomology",
  "equine studies",
  "arts & humanities",
  "industrial design",
  "instructional technology",
  "illustration",
  "radio, tv & film",
  "managerial science",
  "hotel & restaurant management",
  "health sciences",
  "hebrew",
  "speech amp hearing sciences",
  "science education",
  "geosciences",
  "office technology",
  "deaf studies",
  "community health sciences",
  "clinical laboratory sciences",
  "child amp family studies",
  "biotechnology",
  "biostatistics",
  "building construction",
  "english education",
  "modern languages & literature",
  "materials science",
  "nutrition  foods",
  "public policy",
  "psychology  sociology",
  "landscape architecture & regional planning",
  "liberal arts amp sciences",
  "library & information science",
  "legal assisting",
  "study skills",
  "digital media production",
  "dietetics",
  "developmental education",
  "civil & environ engineering",
  "computer graphics",
  "bioengineering",
  "welding technology",
  "english language amp literature",
  "environmental engineering",
  "ecology & evolutionary biology",
  "art  art history",
  "anatomy & physiology",
  "aeronautics",
  "mathematics & statistics",
  "mathematics education",
  "history  political science",
  "hispanic studies",
  "health  human services",
  "physical science",
  "pharmaceutical sciences",
  "personal activities",
  "sports science",
  "surgical technologies",
  "greek",
  "genetics",
  "visual communication design",
  "visual & performing arts",
  "operations management",
  "theatre amp dance",
  "decision science",
  "university community",
  "urban planning",
  "counseling & educational psych",
  "counseling  human services",
  "chemistry & biochemistry",
  "child  family studies",
  "curriculum amp instruction",
  "world languages & cultures",
  "education administration",
  "emt amp paramedic",
  "exercise sport & health ed",
  "art amp art history",
  "art & visual culture",
  "applied music",
  "recreation, parks, & tourism",
  "radiography",
  "rhetoric",
  "russian studies",
  "multicultural studies",
  "hospitality management",
  "near eastern studies",
  "professional studies",
  "public policy & administration",
  "languages & literature",
  "film  television",
  "forensic studies",
  "oral communication",
  "counseling psychology",
  "cognitive science",
  "electrical amp comp. engineering",
  "electronic media",
  "adult health nursing",
  "arts  humanities",
  "air force studies",
  "international relations",
  "rehabilitation counseling",
  "research",
  "modern and classical languages",
  "management & info systems",
  "music business",
  "multidisciplinary studies",
  "human career development",
  "hotel  restaurant management",
  "health  human performance",
  "neuropsychiatry",
  "naval science",
  "public speaking",
  "law enforcement",
  "language arts",
  "supply chain management",
  "secondary education",
  "graphic communication",
  "vocational education",
  "film amp television",
  "foundations",
  "french & italian",
  "organization management",
  "office systems technology",
  "theatre",
  "computer animation",
  "community education",
  "counseling & student affairs",
  "counseling  career planning",
  "cooperative work experience",
  "core humanities",
  "core curriculum",
  "womens  gender studies",
  "womens & gender studies",
  "earth & environmental sciences",
  "ecology  evolutionary biology",
  "emergency management",
  "exercise sport  health ed",
  "agribusiness",
  "arts amp humanities",
  "accountancy",
  "applied health technologies",
  "audio recording technology",
  "industrial studies",
  "respiratory care",
  "radiology",
  "mathematics amp statistics",
  "manufacturing & construction",
  "machinist training",
  "massage therapy",
  "human ecology",
  "philosophy & religion",
  "portuguese",
  "paralegal studies",
  "painting",
  "public affairs",
  "plant & soil science",
  "library  information science",
  "literacy",
  "sociology & anthropology",
  "sculpture",
  "guidance",
  "film studies",
  "foods  nutrition",
  "organizational leadership",
  "theatre arts",
  "travel & tourism",
  "teaching english as a 2nd lang",
  "teaching  learning",
  "television",
  "civil  environ engineering",
  "computer systems technology",
  "consumer family science",
  "construction technology",
  "chemistry amp biochemistry",
  "christian education",
  "business & info. technology",
  "business analysis",
  "black studies",
  "worship",
  "work experience",
  "english & liberal studies",
  "educational technology",
  "electrical & computer engineering",
  "emergency medical services",
  "exercise sport amp health ed",
  "epidemiology",
  "agronomy",
  "art  visual culture",
  "aviation maintenance tech",
  "apparel merchandising",
  "anatomy  physiology",
  "air conditioning  refrig.",
  "automated manufacturing techn.",
  "audiology",
  "interpreter training",
  "residential college",
  "molecular biosciences",
  "media",
  "media & performing arts",
  "math & computer science",
  "management information systems",
  "manufacturing  construction",
  "music technology",
  "human dev & family sciences",
  "history amp political science",
  "health amp human performance",
  "health amp human services",
  "networking",
  "new testament",
  "nutrition & food science",
  "nutrition amp foods",
  "physical & health education",
  "pre-law",
  "park management",
  "public policy amp administration",
  "public relations",
  "peace & conflict studies",
  "learning center",
  "logistics",
  "speech & drama",
  "speech & language pathology",
  "surveying",
  "strategies for success",
  "social  behavioral sciences",
  "science technology & society",
  "game design",
  "visual  performing arts",
  "forensic science",
  "food & nutrition",
  "fashion design",
  "french  italian",
  "transitional studies",
  "textiles & clothing",
  "jazz studies",
  "communication sciences",
  "community health education",
  "counseling amp human services",
  "counseling  educational psych",
  "court reporting",
  "constitutional law",
  "christian ministries",
  "catholic studies",
  "career orientation",
  "business & computer technology",
  "business management",
  "broadcasting tv",
  "behavioral & social sciences",
  "world languages",
  "web development",
  "east asian lang. & literature",
  "ecology",
  "ecology amp evolutionary biology",
  "addiction studies",
  "africana studies",
  "architectural engineering",
  "aviation pilot instructor",
  "academic advisement",
  "academic learning skills",
  "audio production",
  "aerospace engineering",
  "atmospheric sciences",
  "international politics",
  "international affairs",
  "interactive media design",
  "rehabilitative studies",
  "romance languages",
  "modern languages  literature",
  "modern & classical lang & lit.",
  "mathematics  statistics",
  "machine technology",
  "microcomputing",
  "middle eastern studies",
  "mining engineering",
  "museum studies",
  "human relations",
  "human environmental science",
  "honors college",
  "hvac technology",
  "natural science",
  "nutrition  food science",
  "nuclear medicine technology",
  "physician assistant studies",
  "philosophy amp religion",
  "phlebotomy",
  "public service",
  "psychology amp sociology",
  "psychiatry",
  "personal development",
  "peace studies",
  "piano",
  "landscape architecture  regional planning",
  "library amp information science",
  "sports & entertainment management",
  "spanish  portuguese",
  "spanish & portuguese",
  "speech pathology & audiology",
  "social studies",
  "geological sciences",
  "general business",
  "first year seminar",
  "food  nutrition",
  "foods amp nutrition",
  "french studies",
  "occupational safety",
  "theology & religious studies",
  "textiles  clothing",
  "taxation",
  "tv & radio",
  "jewish studies",
  "disability resource center",
  "distance learning",
  "diesel mech.",
  "dentistry",
  "drama",
  "youth ministry",
  "civil amp environ engineering",
  "computer science & c.i.s.",
  "computer science & engineering",
  "computer information technology",
  "computer information tech.",
  "communication design",
  "comm. sciences & disorders",
  "counseling amp career planning",
  "contracts",
  "crafts",
  "classical humanities",
  "clinical sciences",
  "child & youth",
  "carpentry technology",
  "business education & ois",
  "broadcasting radio",
  "womens amp gender studies",
  "engineering & technology",
  "engineering & physics",
  "english  liberal studies",
  "environmental public health",
  "equestrian studies",
  "evangelism",
  "agricultural economics",
  "alcohol & drug studies",
  "art amp visual culture",
  "actuarial science",
  "applied mathematics",
  "applied technology",
  "internation service",
  "interpretation",
  "instruction",
  "recreation parks  tourism",
  "recreation & leisure studies",
  "recreational therapy",
  "radio",
  "radio tv amp film",
  "radio tv  film",
  "radiology technology",
  "rotc",
  "modern languages & literatures",
  "modern languages amp literature",
  "movement sciences",
  "medical terminology",
  "media communications",
  "math  computer science",
  "math & statisitics",
  "materials engineering",
  "materials science & eng.",
  "management amp info systems",
  "manufacturing technology",
  "middle childhood education",
  "music therapy",
  "human dev  family sciences",
  "human dev amp family sciences",
  "hotel amp restaurant management",
  "health services management",
  "heavy equipment technology",
  "neurological sciences",
  "nonprofit management",
  "native american studies",
  "nutrition amp exercise sci",
  "nuclear engineering",
  "philosophy & religious studies",
  "professional development",
  "preaching",
  "public policy  administration",
  "plant pathology",
  "plant  soil science",
  "planning",
  "landscape architecture amp regional planning",
  "landscape studies",
  "languages  literature",
  "languages & literatures",
  "languages & cultures",
  "labor studies",
  "leadership studies",
  "leadership & organization",
  "speech pathology  audiology",
  "speech pathology amp audiology",
  "speech language & hearing",
  "speech language amp hearing",
  "sociology & criminal justice",
  "software engineering",
  "systematic theology",
  "slavic languages & literatures",
  "general science",
  "game development",
  "kinesiology & health",
  "korean",
  "family & consumer sciences",
  "family & social service",
  "family consumer & health sci.",
  "fashion merchandising",
  "french amp italian",
  "funeral service education",
  "organizational studies",
  "organizational behavior",
  "old testament",
  "theological studies",
  "transportation & logistics",
  "trades & technology",
  "technical education",
  "teacher education",
  "journalism & mass comm.",
  "disability & supported ed.",
  "digital media",
  "diesel",
  "dental & radiographic sciences",
  "undergraduate studies",
  "civil procedure",
  "computer science amp engineering",
  "computer sci & info systems",
  "computer sci  info systems",
  "computer  information systems",
  "computer & information sciences",
  "computer & information systems",
  "computer amp information systems",
  "computer technologies",
  "computing  technology",
  "computing & technology",
  "comp networking & telecomm",
  "communication & media studies",
  "communication sciences & disorders",
  "communicative disorders",
  "community studies",
  "comm. sciences  disorders",
  "counseling amp student affairs",
  "counseling amp educational psych",
  "counseling & human development",
  "counseling  human development",
  "consumer family studies",
  "college courses",
  "cyber law",
  "criminal procedure",
  "clothing & textiles",
  "chemistry & physics",
  "chemistry & biology",
  "chemical technology",
  "career tech",
  "business & information systems",
  "business office technology",
  "world civilizations",
  "world languages amp literatures",
  "world languages & literatures",
  "world missions",
  "water & waste water management",
  "east asian languages",
  "earth  environmental sciences",
  "earth amp environmental sciences",
  "english speech foreign lang.",
  "environ safety & occ hlth mgmt",
  "energy systems",
  "educational services",
  "electrical amp computer engineering",
  "economics & finance",
  "exercise amp rehab sciences",
  "exercise & rehab sciences",
  "extended opp. program/service",
  "european studies",
  "advertising design",
  "advising",
  "adv technology",
  "adapted physical education",
  "art amp humanities",
  "art  humanities",
  "art & humanities",
  "arts & administration",
  "arts  administration",
  "arts humanities  comm",
  "arts, humanities & comm",
  "art, media, & design",
  "aviation & technology",
  "academic programs",
  "academic foundations",
  "applied linguistics",
  "applied human sciences",
  "applied studies",
  "analytics & technology",
  "automotive & diesel technology",
  "astronomy & earth sciences",
  "information systems & operations management",
  "information systems  operations manag",
  "intercultural studies",
  "internet professions",
  "instructional administration",
  "imaging science",
  "recreation parks amp tourism",
  "recreation amp leisure studies",
  "recreation  leisure studies",
  "russian & east european studie",
  "motion pictures & television",
  "modern language",
  "mental health",
  "mech. amp aerospace engineering",
  "mech. & aerospace engineering",
  "media  performing arts",
  "medieval studies",
  "merchandising",
  "math  statisitics",
  "math science & engineering",
  "math amp computer science",
  "math amp statisitics",
  "mathematics & physics",
  "management & entrepreneurship",
  "management & operations",
  "management  entrepreneurship",
  "management  info systems",
  "marine & ecological sciences",
  "mass communication",
  "humanities & social sciences",
  "human resource development",
  "human development & family studies",
  "history philosophy religion",
  "history in art",
  "holistic health",
  "health information technology",
  "health, p.e. & athletics",
  "hawaiian",
  "new student seminar",
  "new media art",
  "nutrition & exercise sci",
  "nutrition amp food science",
  "nutrition  exercise sci",
  "physics & chemistry",
  "physics & mathematics",
  "philosophy  religion",
  "process technology",
  "printmaking",
  "public safety",
  "psychology & counseling",
  "petroleum",
  "petroleum engineering",
  "landscape architecture",
  "life sciences",
  "linguistics & language dev.",
  "lgbtq studies",
  "spanish amp portuguese",
  "speech language  hearing",
  "speech  language pathology",
  "supervisory management",
  "strategic management",
  "student success center",
  "student life",
  "study abroad",
  "social amp behavioral sciences",
  "sociology amp criminal justice",
  "sonography",
  "science math & engineering",
  "science technology  society",
  "science, technology, engineering & mathematics",
  "seminars",
  "slavic languages  literatures",
  "greek & roman studies",
  "geological engineering",
  "geomatics technology",
  "gender, women, & sexuality studies",
  "germanic languagesliterature",
  "germanic languages/literature",
  "kinesiology  physical ed.",
  "kinesiology & health studies",
  "vocational nursing",
  "fisheries & wildlife",
  "fisheries biology",
  "film & video",
  "film amp video",
  "film  video",
  "finance amp business law",
  "foreign languages & cultures",
  "food amp nutrition",
  "floral design",
  "family & child sciences",
  "outdoor education",
  "theology  religious studies",
  "trade & apprenticeship",
  "technical communication",
  "textiles amp clothing",
  "teaching amp learning",
  "tourism management",
  "tourism studies",
  "disabled students center",
  "digital media arts & design",
  "dairy science",
  "design technology",
  "decision sciences",
  "drafting  c.a.d.  g.i.s.",
  "urban affairs & public policy",
  "cinema & interactive media",
  "civil & const engineering",
  "civilization",
  "computer science  engineering",
  "computer sci amp info systems",
  "computer sci & industrial tech",
  "computer integrated manufact.",
  "computer network admin",
  "computer application systems",
  "computational science",
  "comp networking  telecomm",
  "comparative religion",
  "counseling  student affairs",
  "conservation",
  "consumer behavior",
  "conflict analysis",
  "conflict resolution",
  "copyright law",
  "corrections",
  "cybersecurity",
  "creative studies",
  "criminal law",
  "criminology & criminal justice",
  "critical studies",
  "crop studies",
  "classical studies",
  "classical  medieval studies",
  "classical & medieval studies",
  "chemistry amp physics",
  "chemistry  biochemistry",
  "chemistry  physics",
  "chem bio  envr engineering",
  "chem bio amp envr engineering",
  "chem bio & envr engineering",
  "child dev & family studies",
  "child dev amp family studies",
  "child & adolescent studies",
  "chiropractic education",
  "church history",
  "care",
  "career & life planning",
  "career & college prep",
  "career  college prep",
  "career  life planning",
  "career amp life planning",
  "career services",
  "cardiorespiratory care",
  "cadd",
  "cabinet & furniture technology",
  "cultural science",
  "culinary arts  hospitality",
  "culinary arts & hospitality",
  "biomedical sciences",
  "biomedical informatics",
  "biochemistry & molecular biology",
  "bioethics",
  "biblical counseling",
  "business  information systems",
  "business  info. technology",
  "business  computer technology",
  "building code enforcement",
  "ballet",
  "barbering",
  "behavioral  social sciences",
  "behavioral amp social sciences",
  "world languages amp cultures",
  "world languages  literatures",
  "womens studies",
];
