name: Pre-release

on:
  push:
    branches: [pre-release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3




      # Astro Project Setup and Build
      - name: Install Astro dependencies and build application
        run: |
          npm install
          npm run build
          cp package.json dist/
          cp package-lock.json dist/
          cp start-astro-server.mjs dist/

        working-directory: unisala-astro

  # Prepare and clear the deployment directory on the server
      - name: Clear deployment directory
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "3.84.137.137"
          username: "ec2-user"
          key: ${{ secrets.UNISALA_LIGHT }}
          port: 22
          script: |
            sudo chown -R ec2-user:ec2-user ~/unisala-web
            sudo rm -rf ~/unisala-web/unisala-astro/{*,.[!.]*,..?*}

            echo "Directory ~/unisala-web cleared"



      # Deploy Astro build artifacts
      - name: Deploy Astro build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "3.84.137.137"
          username: "ec2-user"
          key: ${{ secrets.UNISALA_LIGHT }}
          port: 22
          source: "unisala-astro/dist/*"  # Make sure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/"


      # Install production dependencies for Astro
      - name: Install Astro production dependenciesls
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "3.84.137.137"
          username: "ec2-user"
          key: ${{ secrets.UNISALA_LIGHT }}
          port: 22
          script: |
            cd ~/unisala-web/unisala-astro/dist
            npm install --production

      # Reload Nginx to apply changes
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "3.84.137.137"
          username: "ec2-user"
          key: ${{ secrets.UNISALA_LIGHT }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
            pm2 restart unisala-astro
