name: Test/Release

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install & build
        run: |
          npm i --force
          CI=false NODE_ENV=TEST npm run build
        env:
          NODE_ENV: TEST

      - name: copy file via ssh key
        if: ${{github.ref == 'refs/heads/test'}}
        uses: appleboy/scp-action@master
        with:
          host: "65.0.112.117"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "~/unisala-web"

      - name: ssh
        if: ${{github.ref == 'refs/heads/test'}}
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "65.0.112.117"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd unisala-web/build
            sudo rm -rf /var/www/html/*
            sudo cp -r * /var/www/html