name: Test/Release

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Astro Project Setup and Build
      - name: Install Astro dependencies and build application
        run: |
          npm install
          npm run build
          cp package.json dist/
          cp package-lock.json dist/
          cp start-astro-server.mjs dist/
        working-directory: unisala-astro

      # Prepare and clear the deployment directory on the server
      - name: Clear deployment directory
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "65.0.152.95"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo chown -R ec2-user:ec2-user ~/unisala-web
            sudo rm -rf ~/unisala-web/unisala-astro/{*,.[!.]*,..?*}
            sudo rm -rf ~/unisala-web/unisala-ionic/{*,.[!.]*,..?*}
            echo "Directory ~/unisala-web cleared"

      # Deploy Astro build artifacts
      - name: Deploy Astro build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "65.0.152.95"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"
          target: "~/unisala-web/"

      # Install production dependencies for Astro
      - name: Install Astro production dependencies
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "65.0.152.95"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/unisala-web/unisala-astro/dist
            npm ci --omit dev

      # Reload Nginx to apply changes
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "65.0.152.95"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
            pm2 restart unisala-astro

  semantic-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install semantic-release
        run: |
          cd unisala-astro
          npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git
          
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd unisala-astro
          npx semantic-release