name: Test/Release

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ionic Project Setup and Build
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        working-directory: unisala-ionic

      - name: Install Ionic dependencies and build application
        run: |
          npm install --force
          npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic

      # Astro Project Setup and Build
      - name: Install Astro dependencies and build application
        run: |
          npm install
          npm run build
        working-directory: unisala-astro

     # Prepare and clear the deployment directory on the server with timestamps
      - name: Clear deployment directory
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            date
            echo "Starting to clear deployment directory"
            sudo rm -rf ~/unisala-web/unisala-ionic
            echo "Ionic directory cleared"
            sudo rm -rf ~/unisala-web/unisala-astro
            echo "Astro directory cleared"
            mkdir -p ~/unisala-web/unisala-ionic
            mkdir -p ~/unisala-web/unisala-astro
            echo "Directories recreated"
            sudo chown -R ec2-user:ec2-user ~/unisala-web
            echo "Ownership changed"
            date
            exit 0



      # Deploy Ionic build artifacts
      - name: Deploy Ionic build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"  # Make sure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/"

      # Deploy Astro build artifacts
      - name: Deploy Astro build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"  # Make sure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/"

      # Reload Nginx to apply changes
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
            pm2 restart unisala-astro
            pm2 restart unisala-ionic

