name: Test/Release

on:
  push:
    branches: [micro-frontend]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        working-directory: unisala-ionic

      - name: Install dependencies
        run: npm install --force
        working-directory: unisala-ionic

      - name: Build Ionic Application
        run: npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic

      - name: Ensure directory exists and has correct permissions
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/app
            sudo chown -R ec2-user:ec2-user /var/www/html/app
            echo "Directory prepared"

      - name: Copy build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"
          target: "/var/www/html/app/"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded"
