name: Test/Release

on:
  push:
    branches: [micro-frontend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ionic Project Setup and Build
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        working-directory: unisala-ionic

      - name: Install Ionic dependencies and build application
        run: |
          npm install --force
          npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic

      # Astro Project Setup and Build
      - name: Install Astro dependencies and build application
        run: |
          npm install
          npm run build
        working-directory: unisala-astro

      # Prepare deployment directories on the server and clear old files
      - name: Prepare and clear deployment directories
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Prepare and clear the Ionic app directory
            sudo mkdir -p /var/www/html/app
            sudo chown -R ec2-user:ec2-user /var/www/html/app
            sudo rm -rf /var/www/html/app/*

            # Prepare and clear the Astro directory
            sudo mkdir -p /var/www/html/astro
            sudo chown -R ec2-user:ec2-user /var/www/html/astro
            sudo rm -rf /var/www/html/astro/*

            echo "Directories prepared and cleared for Ionic and Astro"

      # Deploy Ionic build artifacts
      - name: Deploy Ionic build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"  # Make sure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/"

      # Deploy Astro build artifacts
      - name: Deploy Astro build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"  # Make sure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/"

      # Reload Nginx to apply changes
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
            pm2 restart unisala-astro
            pm2 restart unisala-ionic

