name: Test/Release

on:
  push:
    branches: [micro-frontend]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ionic Project
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        working-directory: unisala-ionic

      - name: Install Ionic dependencies
        run: npm install --force
        working-directory: unisala-ionic

      - name: Build Ionic Application
        run: npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic

      # Astro Project
      - name: Install Astro dependencies
        run: npm install
        working-directory: unisala-astro

      - name: Build Astro Application
        run: npm run build
        working-directory: unisala-astro

      # Deployment
      - name: Ensure directory exists and has correct permissions for Ionic
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/app
            sudo chown -R ec2-user:ec2-user /var/www/html/app
            echo "Ionic directory prepared"

      - name: Copy Ionic build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"
          target: "/var/www/html/app/"

      - name: Ensure directory exists and has correct permissions for Astro
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/astro
            sudo chown -R ec2-user:ec2-user /var/www/html/astro
            echo "Astro directory prepared"

      - name: Copy Astro build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"
          target: "/var/www/html/astro/"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
