name: Test

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ionic Project Setup and Build
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        working-directory: unisala-ionic

      - name: Install Ionic dependencies and build application
        run: |
          npm install --force
          npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic

      # Astro Project Setup and Build
      - name: Install Astro dependencies and build application
        run: |
          npm install
          npm run build
        working-directory: unisala-astro

      # Test small file transfer with detailed logging
      - name: Test small file transfer
        uses: appleboy/scp-action@master
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/index.html"  # Test with a small file
          target: "~/unisala-web/test/"
          timeout: 600  # Increase timeout
          command_timeout: 600  # Increase command timeout
          debug: true

      # Deploy Ionic build artifacts with increased timeout
      - name: Deploy Ionic build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"  # Ensure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/unisala-ionic/"
          timeout: 600  # Increase timeout
          command_timeout: 600  # Increase command timeout
          rm: true
          debug: true

      # Deploy Astro build artifacts with increased timeout
      - name: Deploy Astro build artifacts
        uses: appleboy/scp-action@master
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"  # Ensure the path is relative to the GitHub workspace or absolute path
          target: "~/unisala-web/unisala-astro/"
          timeout: 600  # Increase timeout
          command_timeout: 600  # Increase command timeout
          rm: true
          debug: true

      # Reload Nginx to apply changes
      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.200.175.61"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded for both Ionic and Astro"
            pm2 restart unisala-astro
            pm2 restart unisala-ionic
