name: Test/Release

on:
  push:
    branches: [micro-frontend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies for Astro
        run: npm install
        working-directory: unisala-astro  # Specify the correct directory

      - name: Build Astro Application
        run: npm run build
        working-directory: unisala-astro  # Specify the correct directory

      - name: Prepare and Deploy Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/*
            echo "Deployment directory cleared"

      - name: Copy build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"
          target: "/var/www/html/"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded"
