name: Test/Release

on:
  push:
    branches: [test]  # Triggers the workflow on commits to the 'test' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the latest Ubuntu runner environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensures the latest version of the checkout action is used

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Sets up Node.js version 20.x
        with:
          node-version: '20.x'  # Uses Node.js version 20.x
          cache: 'npm'  # Caches npm modules for faster subsequent runs

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
        # Installs Ionic CLI globally so that `ionic` commands can be executed

      - name: Install dependencies
        run: npm install --force
        # Installs project dependencies including local Ionic if needed

      - name: Build Ionic Application
        run: npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST  # Environment variable to signify a test environment build

      - name: Copy files via SSH
        uses: appleboy/scp-action@master  # SCP action to copy files to the remote server
        with:
          host: "65.0.112.117"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/*"  # Source directory to copy from
          target: "/var/www/html"  # Target directory to copy to

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.8  # SSH action to execute remote commands
        with:
          host: "65.0.112.117"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx  # Command to reload Nginx to apply changes