name: Test/Release

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install --force

      - name: Build Ionic Application
        run: npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST

      - name: Copy files via SSH and restart Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "65.0.112.117"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "~/unisala-web"

