name: Test/Release

on:
  push:
    branches: [micro-frontend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install dependencies and build Astro
      - name: Build Astro Application
        run: |
          npm install --force
          npm run build
        working-directory: unisala-astro  # Set the correct directory for Astro operations

      # Install Ionic CLI and dependencies, then build Ionic
      - name: Build Ionic Application
        run: |
          npm install -g @ionic/cli
          npm install --force
          npm run build --prod
        env:
          CI: false
          NODE_ENV: TEST
        working-directory: unisala-ionic  # Set the correct directory for Ionic operations

      # Deployment using SSH and SCP
      - name: Prepare and Deploy Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -rf /var/www/html/astro
            sudo rm -rf /var/www/html/app
            echo "Deployment directories cleared"

      - name: Copy Astro build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-astro/dist/*"
          target: "/var/www/html/astro"

      - name: Copy Ionic build artifacts to the server
        uses: appleboy/scp-action@master
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          source: "unisala-ionic/dist/*"
          target: "/var/www/html/app"

      - name: Reload Nginx
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: "13.201.127.208"
          username: "ec2-user"
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo systemctl reload nginx
            echo "Nginx reloaded"
